experiment_name: plant_disease_offline_models

runs:
  - run_name: mobilenet_v3_small_224
    model_name: mobilenet_v3_small
    batch_size: 2
    learning_rate: 0.001
    epochs: 5
    image_size: 224

  - run_name: mobilenet_v3_large_224
    model_name: mobilenet_v3_large
    batch_size: 2
    learning_rate: 0.001
    epochs: 5
    image_size: 224

  - run_name: efficientnet_b0_224
    model_name: efficientnet_b0
    batch_size: 2
    learning_rate: 0.001
    epochs: 5
    image_size: 224