experiment_name: plant_disease_online_models

runs:
  - run_name: multimodal_resnet50_background_removed_512_epochs30
    model_name: multimodal_resnet50
    batch_size: 6
    learning_rate: 0.001
    epochs: 30
    image_size: 512