# Generated by Django 6.0.3 on 2026-03-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=150)),
                ('is_healthy', models.BooleanField(default=False)),
            ],
        ),
    ]
