# Generated by Django 6.0.3 on 2026-03-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
